version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nestjs_postgres_db
    environment:
      POSTGRES_DB: songs_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: